name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: biomejs/setup-biome@v2
        with:
          version: "2.3.0"
      - name: Run Biome
        run: biome ci .

  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: CI
        run: npm ci

      - name: Test
        run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: CI
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify build output
        run: |
          test -f dist/index.js || (echo "Missing dist/index.js" && exit 1)
          test -f dist/index.cjs || (echo "Missing dist/index.cjs" && exit 1)
          test -f dist/index.d.ts || (echo "Missing dist/index.d.ts" && exit 1)
          test -f dist/index.d.cts || (echo "Missing dist/index.d.cts" && exit 1)
          echo "✓ Build output verified"

  typecheck:
    name: TypeScript Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: CI
        run: npm ci

      - name: Check Types
        run: npx tsc --noEmit
